Release/1.0
Zone-Co/zonebilling-workato-connector pull request #1
Opened 2023-09-20 03:10 UTC by tsantos-zco

2023-09-26 14:43 UTC, pavel-workato reviewed
At the first quite superficial review looks quite good. Left cosmetic suggestions.
and a few general comments:
- `be_kind_of(Object)` is better to replace with more specific matcher.
- double check test coverage

I'll do the seconds iteration with deeper reviewing logic and performance.

2023-09-26 14:43 UTC, pavel-workato commented on connector.rb
> +      options.map do |key, value|
```suggestion
      options.each do |key, value|
```

2023-09-26 14:43 UTC, pavel-workato commented on spec/actions/create_record_spec.rb
> +      expect(output).to be_kind_of(::Object)
```suggestion
      expect(output).to be_kind_of(::Hash)
```

 `::Object` is a base class of almost everything, "Hash" is better for hash-like instances.

2023-09-26 14:43 UTC, pavel-workato commented on spec/actions/create_records_batch_spec.rb
> +    subject(:output) {output = action.execute(settings, {
```suggestion
    subject(:output) { action.execute(settings, {
```

2023-09-26 14:43 UTC, pavel-workato commented on spec/actions/update_record_spec.rb
File name is `update_record_spec.rb`, but it contains tests for `actions/create_record`

2023-09-26 14:43 UTC, pavel-workato commented on spec/actions/upsert_record_spec.rb
Same mismatch of filename and tested acton.

2023-09-26 14:43 UTC, pavel-workato commented on spec/actions/upsert_records_batch_spec.rb
> +    subject(:output) {output = action.execute(settings, {
```suggestion
    subject(:output) { action.execute(settings, {
```

2023-09-26 14:43 UTC, pavel-workato commented on spec/connector_spec.rb
> +      subject(:output) {connector.test(settings)}
```suggestion
      subject(:output) { connector.test(settings) }
```

2023-09-26 16:43 UTC, tsantos-zco commented
Thank you for comments @pavel-workato! I updated the branch with your revisions [per this commit](https://github.com/Zone-Co/zonebilling-workato-connector/pull/1/commits/1f1d0725f9e46b646ee20fc0b20396c5617444f6)

2023-09-28 14:26 UTC, pavel-workato approved these changes
Looks solid. Thanks! 👍

2023-09-28 14:26 UTC, pavel-workato commented on spec/actions/upsert_records_batch_spec.rb
> +RSpec.describe 'actions/update_records_batch', :vcr do
```suggestion
RSpec.describe 'actions/upsert_records_batch', :vcr do
```

2023-09-28 14:26 UTC, pavel-workato commented on spec/actions/upsert_records_batch_spec.rb
> +  let(:action) { connector.actions.update_records_batch }
```suggestion
  let(:action) { connector.actions.upsert_records_batch }
```

2023-09-28 14:26 UTC, pavel-workato commented on spec/actions/upsert_records_batch_spec.rb
> +    subject(:process_output) { get.execute(settings, {
`process_output` is not used. Maybe can remove unless needed for something in future.

2023-09-28 14:26 UTC, pavel-workato commented on spec/actions/create_records_batch_spec.rb
> +  let(:action) { connector.actions.update_records_batch }
```suggestion
  let(:action) { connector.actions.create_records_batch }
```

2023-09-28 14:26 UTC, pavel-workato commented on spec/actions/create_records_batch_spec.rb
> +RSpec.describe 'actions/update_records_batch', :vcr do
```suggestion
RSpec.describe 'actions/create_records_batch', :vcr do
```

2023-10-06 13:13 UTC, szaretsky requested changes

2023-10-06 13:41 UTC, tsantos-zco commented on connector.rb
> +        call(:post, connection, input, 'create')
There is not limit! We receive the request and save it in storage to process via our server-side Map/Reduce script to maximize concurrency.

2023-10-06 13:52 UTC, tsantos-zco commented on connector.rb
>      authorization: {
Resolve per [this commit](https://github.com/Zone-Co/zonebilling-workato-connector/pull/1/commits/d4caf58bc3096e5d45f4fe80da9fbff566741502). Thanks @szaretsky !

2023-10-08 15:40 UTC, szaretsky reviewed
I'm sorry, that was missed at the first pass.
Fixtures should be moved to spec folder since they are a part of test suite

2023-10-08 15:41 UTC, szaretsky approved these changes
Please ignore previous comment. 
PR looks good. Thanks

2023-10-09 00:11 UTC, bennettgo reviewed
@tsantos-zco for the logo for your connector, I see its the orange logo but ZoneBilling shows as Blue on your website. Could I confirm what logo colours you want?

2023-10-09 00:11 UTC, bennettgo commented on Connector_details.md
> +This connector was built and is supported by Zone & Company Software Consulting LLC. Send bug reports and enhancement requests to [Zone & Co. Support](https://www.zoneandco.com/support-hub).
@tsantos-zco since your contact details as in the README.md which makes sense to me, can we move this section to the README.md as well? Then remove this file. 

I'd ask for 3 more pieces of information
1. Connector Name - (Shown on the Workato UI)
2. Support email 
3. Connector search keyword alias (Up to three) - For example if someone searches "Billing" or "Invoice"
4. Categories for our integration page

You can pick from these:
Sales And Marketing
Product/Project Management
Customer Service
HR
Finance And Accounting
Developer
DevOps/IT
Productivity
AI/Machine Learning
Operations
Collaboration
Recipe Tools
Other

2023-10-10 01:10 UTC, tsantos-zco commented on Connector_details.md
> +This connector was built and is supported by Zone & Company Software Consulting LLC. Send bug reports and enhancement requests to [Zone & Co. Support](https://www.zoneandco.com/support-hub).
@bennettgo , this has been resolved [per this commit](https://github.com/Zone-Co/zonebilling-workato-connector/pull/1/commits/6177d19729c8db582acb6d6016b72ae07a4812df). We kept the `./Connector_details.md` as it is used in our internal deployment when we execute `workato push`. 

All needed information is updated in the `./README.md`

For the logo, we want to use the Red Logo in the repository, we do not want to use the blue logo.

2023-10-10 01:11 UTC, tsantos-zco commented
@bennettgo , please see [my comment here](https://github.com/Zone-Co/zonebilling-workato-connector/pull/1#discussion_r1351126910)

2023-11-28 20:29 UTC, tsantos-zco commented
Merging this in as it is now complete and releasede! Thanks @bennettgo, @szaretsky & @pavel-workato !! 🥳

2023-11-28 20:30 UTC, merged